default: &default
  adapter: postgresql
  username: postgres
  password: root
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pe_development

test:
  <<: *default
  database: pe_test

production:
  <<: *default
  database: pe_production
  username: pe
  password: <%= ENV['PE_DATABASE_PASSWORD'] %>
